export default {
  pages: [
    'pages/index/index',
    'pages/Button/index',
    'pages/Icon/index',
    'pages/Loading/index',
    'pages/Space/index',
    'pages/Grid/index',
    'pages/Image/index',
    'pages/List/index',
    'pages/Tag/index',
    'pages/Badge/index',
    'pages/Card/index',
    'pages/NoticeBar/index',
    'pages/PageIndicator/index',
    'pages/Steps/index',
    'pages/Empty/index',
    'pages/SafeArea/index',
    'pages/Divider/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
};
