export default {
  pages: [
    'pages/index/index',
    'pages/Button/index',
    'pages/Icon/index',
    'pages/Loading/index',
    'pages/Space/index',
    'pages/Grid/index',
    'pages/Image/index',
    'pages/List/index',
    'pages/Tag/index',
    'pages/Badge/index',
    'pages/Card/index',
    'pages/NoticeBar/index',
    'pages/PageIndicator/index',
    'pages/Steps/index',
    'pages/Empty/index',
    'pages/SafeArea/index',
    'pages/Divider/index',
    'pages/Result/index',
    'pages/AutoCenter/index',
    'pages/DesenseText/index',
    'pages/NavBar/index',
    'pages/ProgressBar/index',
    'pages/ProgressCircle/index',
    'pages/SideBar/index',
    'pages/IndexBar/UnControlled/index',
    'pages/IndexBar/Controlled/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
};
