export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/useState/index',
    'pages/useEffect/index',
    'pages/useRef/index',
    'pages/useReducer/index',
    'pages/useContext/index',
    'pages/useRequest/index',
    'pages/useRequest/basic/index',
    'pages/useRequest/basic/manualRun',
    'pages/useRequest/basic/manualRunAsync',
    'pages/useRequest/basic/lifeCycle',
    'pages/useRequest/basic/refresh',
    'pages/useRequest/basic/mutate',
    'pages/useRequest/basic/params',
    'pages/useRequest/basic/cancel',
    'pages/useRequest/cache/cacheKey',
    'pages/useRequest/cache/clearCache',
    'pages/useRequest/cache/params',
    'pages/useRequest/cache/setCache',
    'pages/useRequest/cache/share',
    'pages/useRequest/cache/staleTime',
    'pages/useRequest/debounce/index',
    'pages/useRequest/loadingDelay/index',
    'pages/useRequest/polling/index',
    'pages/useRequest/ready/index',
    'pages/useRequest/ready/manualReady',
    'pages/useRequest/refreshDeps/index',
    'pages/useRequest/refreshOnWindowFocus/index',
    'pages/useRequest/retry/index',
    'pages/useRequest/throttle/index',
    // env
    'pages/environment/useEnv/index',
    // basic
    'pages/basic/useVisible/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Taro-Hooks',
    navigationBarTextStyle: 'black',
  },
});
