tasks:
  - name: dependencies
    init: >
      pnpm install &&
      gp sync-done bundle
  - name: dev server
    init: gp sync-await bundle
    command: cd website && yarn docusaurus:start

ports:
  - port: 3000
    onOpen: open-preview
