export const components = {
  basic: [
    '/ant-mobile-taro/src/components/button',
    '/ant-mobile-taro/src/components/icon',
    '/ant-mobile-taro/src/components/list',
    '/ant-mobile-taro/src/components/space',
  ],
  dataDisplay: [
    '/ant-mobile-taro/src/components/badge',
    '/ant-mobile-taro/src/components/card',
    '/ant-mobile-taro/src/components/image',
    '/ant-mobile-taro/src/components/image-viewer',
    '/ant-mobile-taro/src/components/infinite-scroll',
    '/ant-mobile-taro/src/components/notice-bar',
    '/ant-mobile-taro/src/components/page-indicator',
    '/ant-mobile-taro/src/components/popover',
    '/ant-mobile-taro/src/components/steps',
    '/ant-mobile-taro/src/components/swiper',
    '/ant-mobile-taro/src/components/tag',
    '/ant-mobile-taro/src/components/water-mark',
  ],
  dataEntry: [
    '/ant-mobile-taro/src/components/check-list',
    '/ant-mobile-taro/src/components/checkbox',
    '/ant-mobile-taro/src/components/form',
    '/ant-mobile-taro/src/components/input',
    '/ant-mobile-taro/src/components/picker',
    '/ant-mobile-taro/src/components/radio',
    '/ant-mobile-taro/src/components/rate',
    '/ant-mobile-taro/src/components/search',
    '/ant-mobile-taro/src/components/selector',
    '/ant-mobile-taro/src/components/slider',
    '/ant-mobile-taro/src/components/stepper',
    '/ant-mobile-taro/src/components/switch',
    '/ant-mobile-taro/src/components/text-area',
  ],
  feedback: [
    '/ant-mobile-taro/src/components/action-sheet',
    '/ant-mobile-taro/src/components/dialog',
    '/ant-mobile-taro/src/components/empty',
    '/ant-mobile-taro/src/components/error-block',
    '/ant-mobile-taro/src/components/loading',
    '/ant-mobile-taro/src/components/mask',
    '/ant-mobile-taro/src/components/progress-bar',
    '/ant-mobile-taro/src/components/progress-circle',
    '/ant-mobile-taro/src/components/pull-to-refresh',
    '/ant-mobile-taro/src/components/result',
    '/ant-mobile-taro/src/components/swipe-action',
    '/ant-mobile-taro/src/components/toast',
  ],
  navigationAndLayout: [
    '/ant-mobile-taro/src/components/capsule-tabs',
    '/ant-mobile-taro/src/components/collapse',
    '/ant-mobile-taro/src/components/divider',
    '/ant-mobile-taro/src/components/floating-panel',
    '/ant-mobile-taro/src/components/grid',
    '/ant-mobile-taro/src/components/index-bar',
    '/ant-mobile-taro/src/components/jumbo-tabs',
    '/ant-mobile-taro/src/components/nav-bar',
    '/ant-mobile-taro/src/components/popup',
    '/ant-mobile-taro/src/components/side-bar',
    '/ant-mobile-taro/src/components/tab-bar',
    '/ant-mobile-taro/src/components/tabs',
  ],
  other: ['/ant-mobile-taro/src/components/config-provider'],
  experimental: [
    // '/ant-mobile-taro/src/components/what-is-experimental',
    '/ant-mobile-taro/src/components/auto-center',
    '/ant-mobile-taro/src/components/desense-text',
    '/ant-mobile-taro/src/components/dropdown',
    '/ant-mobile-taro/src/components/ellipsis',
    '/ant-mobile-taro/src/components/image-uploader',
    '/ant-mobile-taro/src/components/number-keyboard',
    '/ant-mobile-taro/src/components/picker-view',
    '/ant-mobile-taro/src/components/safe-area',
    '/ant-mobile-taro/src/components/tree-select',
    '/ant-mobile-taro/src/components/virtual-input',
    // '/ant-mobile-taro/src/components/scroll-mask',
  ],
};
